version: "3.0"

services:
    laravel-app:
        build: app/
        links:
            - redis
            - mongo
        ports:
            - 80:80
        volumes:
            - /app
    redis:
        image: redis
    mongo:
        image: mongo